{% set name = "terraform-docs" %}
{% set version = "0.16.0" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/segmentio/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e370fd106ca74caebc8632834cc28412a3a6a160952392da71f213515bba2085

build:
  number: 1
  script:
    - go install -v -ldflags "-X main.version={{ version }}" .  # [not arm64]
    # Call "go build" directly when cross-compiling because GOBIN cannot be set for "go install" when cross-compiling
    # See https://github.com/golang/go/issues/57485
    - go build -o "{{ environ.get('PREFIX') }}/bin/terraform-docs" -v -ldflags "-X main.version={{ version }}" .  # [arm64]

requirements:
  build:
    - {{ compiler("go") }} 1.16

test:
  commands:
    - which terraform-docs  # [not win]
    - where terraform-docs  # [win]
    - terraform-docs --help

about:
  home: https://github.com/segmentio/terraform-docs

  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate docs from Terraform modules

extra:
  recipe-maintainers:
    - mxr-conda
    - andrew-mcgrath
    - pierrsc
