{% set version = "0.8.2" %}
{% set name = terraform-docs %}


package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/segmentio/terraform-docs/archive/v{{version}}.tar.gz
    sha256: 005957c5c5d56a27e60ca735128231f68c3f099b433a7041a0f1591bee59fbd0

build:
  number: 0
  script:
    - go install -v

requirements:
  build:
    - {{ compiler("go") }}

test:
  commands:
    - which terraform-docs  # [not win]
    - where terraform-docs  # [win]
    - terraform-docs --help

about:
  home: https://github.com/segmentio/terraform-docs
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: 'Generate docs from Terraform modules'

extra:
  recipe-maintainers:
    - andrew-mcgrath
    - pierrsc
