{% set import_path = "github.com/segmentio/terraform-docs" %}
{% set version = "0.8.2" %}
{% set name = import_path.split('/')[-1] %}
{% set pkg_src = ('src/'+import_path).replace("/", os.sep) %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
    folder: {{ pkg_src }}
    url: https://{{ import_path }}/archive/v{{version}}.tar.gz
    sha256: 005957c5c5d56a27e60ca735128231f68c3f099b433a7041a0f1591bee59fbd0

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v
    - ldflags "-X main.version={{ version }}"

requirements:
  build:
    - {{ compiler("go") }}

test:
  commands:
    - which terraform-docs  # [not win]
    - where terraform-docs  # [win]
    - terraform-docs --help

about:
  home: https://{{ import_path }}
  license: MIT
  license_family: MIT
  license_file: {{ pkg_src }}/LICENSE
  summary: 'Generate docs from Terraform modules'

extra:
  recipe-maintainers:
    - andrew-mcgrath
    - pierrsc
