{% set name = "terraform-docs" %}
{% set version = "0.21.0" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/terraform-docs/terraform-docs/archive/v{{ version }}.tar.gz
  sha256: e8180d74662707b2643930aee7ba012a29ad767ef55fd3321d6a9f3ce7fa79b8

build:
  number: 0
  script_env:
    - BINARY_FILEPATH={{ PREFIX }}/bin/terraform-docs.exe  # [win]
    - BINARY_FILEPATH={{ PREFIX }}/bin/terraform-docs      # [not win]

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - go-licenses
    - posix                  # [win]

test:
  requires:
    - ripgrep
  commands:
    - terraform-docs --help
    - terraform-docs --version | rg {{ version }}

about:
  home: https://github.com/terraform-docs/terraform-docs

  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate docs from Terraform modules

extra:
  recipe-maintainers:
    - mxr-conda
    - andrew-mcgrath
    - pierrsc
    - dhirschfeld
