{% set name = "terraform-docs" %}
{% set version = "0.24.0" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/terraform-docs/terraform-docs/archive/v{{ version }}.tar.gz
  sha256: e3c971a1f2a02732d964e19e65c901b4e02cca62c4b748c05d22e9690d055540

build:
  number: 0
  script_env:
    - BINARY_FILEPATH={{ PREFIX }}/bin/terraform-docs.exe  # [win]
    - BINARY_FILEPATH={{ PREFIX }}/bin/terraform-docs      # [not win]

requirements:
  build:
    - {{ compiler("go-nocgo") }}
    - go-licenses
    - posix                  # [win]

test:
  requires:
    - ripgrep
  commands:
    - terraform-docs --help
    - terraform-docs --version | rg {{ version }}

about:
  home: https://github.com/terraform-docs/terraform-docs

  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate docs from Terraform modules

extra:
  recipe-maintainers:
    - mxr-conda
    - andrew-mcgrath
    - pierrsc
    - dhirschfeld
