{% set name = "terraform-docs" %}
{% set version = "0.12.0" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/segmentio/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7dd982b201317c58db71a9d2675ed61ad0f545aa6b7ed0408e2f729f4cac1a70

build:
  number: 0
  script:
    - go install -v -ldflags "-X main.version={{ version }}" .

requirements:
  build:
    - {{ compiler("go") }} 1.13

test:
  commands:
    - which terraform-docs  # [not win]
    - where terraform-docs  # [win]
    - terraform-docs --help

about:
  home: https://github.com/segmentio/terraform-docs

  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate docs from Terraform modules

extra:
  recipe-maintainers:
    - andrew-mcgrath
    - pierrsc
