travis:
  secure:
    BINSTAR_TOKEN: wBBkqW7XOGwARc24EA+hb3z0IOYwpjzNk7Sp0LZBmsteSdzm0z8K4LUsCVzS33HqZMFHxcW/HPnWwUJcomo3mfrR7Dfbxg4rLT33NG/KoGcxTht7JJYJ//DYG3PH9d96AU2cdLymvl24T4PUkdLZk4X9PUuwh369N8uQ1kRUQ3Mz0ujcElDxKEWKtvCNAyJhth62Go3YaqSJqaywqnetDXFpY053jP+cz/8YOU6m2XU+bya5cwQKUw2Whbuq2Iit0wKsnWhVs7ytgetW7QEfbFxm16UvUZ1Ljj+WMIN/VmACWVtNg6pPaE8A8soJFPZpOp5zPM5C04jPIeAvhVnfPwB/eattJJE/NwZzEKOf7VgxfMZjcsv1RkrXVm69iEGZGImR/Q93Tz3wpLElvRVMwSaS4lW/9TeDYGiHKM49NnlZdBeOzgVQRttin7NEmhoY9YlFsGJmFhBy4DpPIbnsjD9Fwpnyd/MR7snyVLW2hfa6R+d8UVkJS5Ji0g6rjUCgVzZl+tvNUzHaDoX0XDcOgJhDsEV/BA/9PNPlhYpjQhY7WlRVmn2EDq2sclj8hRS8ipN3JRbrLJx0ZawwB2Blvh0HggZ6X+sXZ79TuwYVnwiKDkQDJuOo7CMVfAu9nvwnhVyBpwPsCZ2Z60K1IVCbn2JBKzBb2gPyGAgtSTAftbo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
